-- MySQL Script generated by MySQL Workbench
-- jue 05 ene 2023 11:35:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema baseDatos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema baseDatos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `baseDatos` ;
USE `baseDatos` ;

-- -----------------------------------------------------
-- Table `baseDatos`.`Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseDatos`.`Room` (
  `idRoom` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRoom`),
  UNIQUE INDEX `Room_UNIQUE` (`idRoom` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseDatos`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseDatos`.`User` (
  `idUser` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `Room_idRoom` INT UNSIGNED NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC) VISIBLE,
  INDEX `fk_User_Room_idx` (`Room_idRoom` ASC) VISIBLE,
  CONSTRAINT `fk_User_Room`
    FOREIGN KEY (`Room_idRoom`)
    REFERENCES `baseDatos`.`Room` (`idRoom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseDatos`.`Partida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseDatos`.`Partida` (
  `idPartida` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `User_Room_idRoom` INT UNSIGNED NOT NULL,
  `User_idUser` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idPartida`, `User_Room_idRoom`, `User_idUser`),
  UNIQUE INDEX `idPartida_UNIQUE` (`idPartida` ASC) VISIBLE,
  INDEX `fk_Partida_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Partida_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `baseDatos`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseDatos`.`UpdateGrid`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseDatos`.`UpdateGrid` (
  `frame` INT NOT NULL,
  `x` INT NOT NULL,
  `y` INT NOT NULL,
  `color` INT NOT NULL,
  `Partida_idPartida` INT UNSIGNED NOT NULL,
  `Partida_User_idUser` INT UNSIGNED NOT NULL,
  `Partida_User_Room_idRoom` INT UNSIGNED NOT NULL,
  CONSTRAINT `fk_UpdateGrid_Partida1`
    FOREIGN KEY (`Partida_idPartida` , `Partida_User_Room_idRoom`)
    REFERENCES `baseDatos`.`Partida` (`idPartida` , `User_Room_idRoom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
